version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  aws-ebcli: circleci/aws-elastic-beanstalk@2.0.1

triggers:
  - filters:
      branches:
        only:
          - main
jobs:
  build:
    docker:
      - image: cimg/node:14.15
    steps:
      - node/install:
        node-version: '14.15.1'
      - checkout
      - aws-cli/setup
      - aws-ebcli/setup
      - run:
          name: Install Server Dependencies
          command: npm run backend.install
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend.install
      - run:
          name: Test
          command: npm run frontend.test
      - run:
          name: Build Server
          command: npm run backend.build
      - run:
          name: build Frontend
          command: npm run frontend.build
      - run:
          name: Desplay AWS Configure
          command: aws configure list
      - run:
          name: deploy frontend to aws
          command: npm run frontend.deploy

      - run:
          name: deploy backend API to aws
          command: npm run backend.deploy